[package]
name = "my-keyring-server"
version = "0.1.0"
authors = ["Lolo_32 <lol.b@free.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.hyper]
version = "0.14.5"
features = [
    "full"
]

[dependencies.lazy_static]
version = "1.4.0"

[dependencies.my-keyring-shared]
path = "../my-keyring-shared"

[dependencies.serde_json]
version = "1.0"

[dependencies.tokio]
version = "1.5.0"
features = [
    "fs",
    "parking_lot",
    "rt-multi-thread",
    "sync"
]

[dependencies.ulid]
version = "0.4.1"
